export const theme = {
  colors: {
    primary: '#2679FF',
    secondary: '#0084ff',
    danger: '#FE3939',
    success: '#4b0',
    warning: 'yellow',
    title: '#000',
    black: '#000',
    white: '#fff',
    gray: '#E4E4E6',
    subtitle: '#555',
    description: '#8E8E8E',
    badgeText: '#fff',
    textGreyColor: '#83868B',
    badgeBackground: '#5546FF',
    storyBorder: '#00f',
    searchBackground: '#f0f0f0',
    searchText: '#444',
    searchIcon: '#999',
    inputBackground: '#E9E9E9',
    inputText: 'black',
    inputIcon: '#444',
    sendBackground: '#0084ff',
    sendIcon: '#fff',
    tabBackground: '#fff',
    activeTabTitle: 'black',
    inactiveTabTitle: 'gray',
    tabIndicator: '#0084ff',
    tabPageBackground: '#fff',
    tabItemBackground: '#fff',
    halfOpacitySecondary: 'rgba(240, 149, 17, 0.5)',
    halfOpacityPrimary: 'rgba(0, 132, 255, 0.5)',
  },
  fontSize: {
    title: 18,
    subtitle: 13,
    description: 15,
  },
};
