import {StyleSheet} from 'react-native';
import {theme} from '../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 44,
    paddingTop: 60,
    backgroundColor: '#F4F4F4',
  },
  pravicaLogo: {width: '50%', resizeMode: 'contain'},
  imageHeader: {
    width: 90,
    height: 80,
    marginBottom: 40,
  },
  card: {
    backgroundColor: 'white',
    padding: 35,
    paddingTop: 50,
    paddingBottom: 53,
    marginTop: 50,
    borderRadius: 20,
  },
  description: {
    color: '#000',
    fontSize: 14,
    opacity: 0.5,
    marginBottom: 10,
  },
  cardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
    marginVertical: 10,
  },
  image: {
    width: 57,
    height: 57,
    marginRight: 20,
    resizeMode: 'contain',
  },
  title: {
    color: theme.colors.black,
    fontSize: 24,
    fontWeight: '700',
    marginVertical: 10,
  },
  textInput: {
    backgroundColor: '#ECF0F1',
    height: 100,
    borderRadius: 12,
    marginTop: 24,
    padding: 16,
    paddingTop: 16,
    fontSize: 14,
    color: 'black',
  },
  loginButton: {
    padding: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderRadius: 10,
    backgroundColor: theme.colors.badgeBackground,
    height: 48,
  },
  loginLogo: {width: 24, height: 24, marginRight: 9},
  buttonText: {color: theme.colors.white, fontSize: 14},
  seetTextRed: {color: theme.colors.danger, fontSize: 14, marginTop: 8},
  fieldRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cell: {
    width: '23%',
    aspectRatio: 1,
    // paddingTop: 15,
    textAlign: 'center',
    textAlignVertical: 'center',
    marginLeft: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    borderColor: '#DEDEDE',
    borderWidth: 1,
  },
  textChild: {
    fontSize: 30,
    fontWeight: '700',
  },
  toggle: {
    width: 55,
    height: 55,
    lineHeight: 55,
    fontSize: 24,
    textAlign: 'center',
  },
  focusCell: {
    shadowColor: '#3CA5FF',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.9,
    shadowRadius: 3,
    borderColor: '#DEDEDE',
    elevation: 5,
  },
  errorTextRed: {
    color: theme.colors.danger,
    fontSize: 14,
    marginTop: 16,
    marginLeft: 16,
  },
  confirmPinCode: {
    fontSize: 14,
    color: 'black',
    marginTop: 10,
  },
});
