import {Platform, StyleSheet} from 'react-native';
import {theme} from '../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 44,
    paddingTop: 64,
    paddingHorizontal: 28,
    backgroundColor: 'white',
  },
  loginButton: {
    padding: 8,
    backgroundColor: theme.colors.badgeBackground,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderRadius: 10,
    width: '100%',
    marginTop: 45,
    height: 48,
    paddingHorizontal: 20,
    shadowColor: '#000000',
    shadowOffset: {height: 1, width: 0},
    shadowOpacity: 0.75,
    shadowRadius: 1,
  },
  loginLogo: {width: 24, height: 24},
  buttonText: {color: theme.colors.white, fontSize: 14},
  cardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
    marginVertical: 10,
    marginBottom: 20,
  },
  text: {
    color: 'black',
    fontSize: 20,
    textAlign: 'center',
    marginVertical: 16,
  },
  desc: {
    color: 'black',
    fontSize: 18,
    textAlign: 'left',
    marginVertical: 16,
  },
  cell: {
    width: 55,
    height: 55,
    lineHeight: 55,
    fontSize: 30,
    fontWeight: '700',
    textAlign: 'center',
    marginLeft: 8,
    borderRadius: 12,
    borderColor: '#707070',
    borderWidth: 1,
  },
  focusCell: {
    shadowColor: '#3CA5FF',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.9,
    shadowRadius: 3,
    borderColor: Platform.OS === 'ios' ? '#707070' : '#5546FF',
  },
  errCell: {
    borderColor: '#FE3939',
  },
  textInput: {
    backgroundColor: '#E0E0E0',
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
    textAlignVertical: 'center',
    borderRadius: 15,
    marginTop: 12,
    padding: 16,
    paddingTop: 16,
    fontSize: 14,
    color: 'black',
  },
  back: {width: 25, height: 15, marginRight: 16},
  view: {marginTop: 20},
});
